# Generated by Django 3.2.9 on 2021-12-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('cuerpo', models.CharField(max_length=250)),
                ('fecha_creacion', models.TimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='post')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
