# Generated by Django 4.0a1 on 2021-12-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('cuerpo', models.CharField(max_length=250)),
                ('fecha_creacion', models.TimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.categoria')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
