# Generated by Django 3.2.9 on 2021-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_s', models.CharField(max_length=250)),
                ('cuerpo_s', models.CharField(max_length=250)),
                ('fecha_creacion_s', models.CharField(max_length=30)),
                ('autor_s', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'secretos',
            },
        ),
    ]
